apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: etri17i2y-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:d2242d41b1272fb56d04d4856963c307986f18cf@sha256:82b8e28b1d7d2573a60070ed6c7ffc3e4a900f7340a8e59e74f6c6db138ada7e
          name: container-image
